//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Manga.Server.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailTemplates() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Manga.Server.Resources.EmailTemplates", typeof(EmailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ja&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;交換申請のお知らせ&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body style=&quot;font-family: Arial, sans-serif; line-height: 1.6; color: #333333; max-width: 600px; margin: 0 auto; padding: 20px;&quot;&gt;
        ///    &lt;div style=&quot;background-color: #f4f4f4; padding: 20px; border-radius: 5px; margin-bottom: 20px;&quot;&gt;
        ///        &lt;h2 style=&quot;color: #4a4a4a; margin-top: 0;&quot;&gt;交換申請のお知らせ&lt;/h2&gt;
        ///        &lt;p style=&quot;margin-b [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ConsolidatedRequestMessage {
            get {
                return ResourceManager.GetString("ConsolidatedRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;style&gt;
        ///        body {{ font-family: &apos;Arial&apos;, sans-serif; font-size: 14px; color: #333; }}
        ///        .header {{ color: #444; font-size: 16px; font-weight: bold; }}
        ///        .content {{ margin-top: 20px; }}
        ///        .footer {{ margin-top: 40px; font-size: 12px; color: #666; }}
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;div class=&quot;email-container&quot;&gt;
        ///        &lt;div class=&quot;header&quot;&gt;{0}さん&lt;/div&gt;
        ///        &lt;div class=&quot;content&quot;&gt;
        ///            トカエルをご利用いただきありがとうございます。&lt;br&gt;&lt;br&gt;
        ///            以下 [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString("ContactMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;ja&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;UTF-8&quot;&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;&gt;
        ///    &lt;title&gt;【トカエル】漫画交換が成立しました！配送手続きのお願い&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///        }
        ///        .container {
        ///            max-width: 600px;
        ///            margin: 0 auto;
        ///            padding: 20px;
        ///        }
        ///        h1 {
        ///            color: #E97032;
        ///        }
        /// [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MatchMessage {
            get {
                return ResourceManager.GetString("MatchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トカエルをご利用いただきありがとうございます。&lt;br /&gt;
        ///仮登録が完了しました。&lt;br /&gt;
        ///&lt;br /&gt;
        ///以下のリンクをクリックすることでアカウントの登録が完了し、
        ///すべてのサービスをご利用いただけます。&lt;br /&gt;
        ///
        ///&lt;a href=&quot;{0}&quot;&gt;{0}&lt;/a&gt;
        ///&lt;br /&gt;
        ///トカエルサポートチーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RegisterEmailMessage {
            get {
                return ResourceManager.GetString("RegisterEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   // Resources/EmailTemplates.resx ファイル内
        ///
        ///&lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;data name=&quot;ReportMessage&quot; xml:space=&quot;preserve&quot;&gt;
        ///    &lt;value&gt;
        ///&lt;![CDATA[
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&apos;ja&apos;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&apos;UTF-8&apos;&gt;
        ///    &lt;meta name=&apos;viewport&apos; content=&apos;width=device-width, initial-scale=1.0&apos;&gt;
        ///    &lt;title&gt;新しい通報通知&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {{
        ///            font-family: Arial, sans-serif;
        ///            line-height: 1.6;
        ///            color: #333;
        ///            max-width: 600px;
        ///         [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReportMessage {
            get {
                return ResourceManager.GetString("ReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   トカエルをご利用いただきありがとうございます。
        ///
        ///{0}さんの出品「{1}」に交換申請がありました。
        ///
        ///申請を受け入れると相手の出品「{2}」と交換することができます。
        ///
        ///詳細を確認してほしい作品を手に入れましょう！
        ///&lt;a href=&quot;https://localhost:5173/notification&quot;&gt;https://localhost:5173/notification&lt;/a&gt;
        ///
        ///トカエルサポートチーム に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string RequestMessage {
            get {
                return ResourceManager.GetString("RequestMessage", resourceCulture);
            }
        }
    }
}
